/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        google()
    }
    versionCatalogs {
        register("libs") {
            from(files("gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = "fraud-detection"
include("app", "list", "utilities")
include("core")
include("ingestion")
include("detection-engine")
include("decision")
include("api")
include("persistence")
include("common")
include("plaid-integration")
