/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.springframework.boot") version "3.2.4"
    id("io.spring.dependency-management") version "1.1.4"
}

group = "com.bragdev"
version = "0.0.1-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation(project(":core"))
    implementation(project(":utilities"))
    implementation("org.apache.commons:commons-text")
    implementation ("org.springframework.boot:spring-boot-starter-web")
    implementation ("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation ("org.springframework.boot:spring-boot-starter-validation")
    implementation ("org.springframework.boot:spring-boot-starter-security")
    implementation ("org.springframework.boot:spring-boot-starter")
    implementation ("org.projectlombok:lombok")
    runtimeOnly ("org.postgresql:postgresql")
    runtimeOnly ("com.h2database:h2")
    annotationProcessor ("org.projectlombok:lombok")
    testImplementation ("org.springframework.boot:spring-boot-starter-test")
}

application {
    // Define the main class for the application.
    mainClass = "com.bragdev.fraud.FraudDetectionApplication"
}
