/*
 * This source file was generated by the Gradle 'init' task
 */
package com.bragdev.fraud-detection;

import com.bragdev.list.LinkedList;

import static com.bragdev.utilities.StringUtils.join;
import static com.bragdev.utilities.StringUtils.split;
import static com.bragdev.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class FraudDetectionApplication {
  public static void main(String[] args) {
    LinkedList tokens;
    tokens = split(getMessage());
    String result = join(tokens);
    System.out.println(WordUtils.capitalize(result));
  }
}
